RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "orders#index"

  resources :orders, only: [:index, :show, :new, :edit, :create] do
    collection do
      post :expire
    end
    member do
      post :add_item
      post :remove_item
      post :pay
      post :cancel
      get :edit_discount
      post :update_discount
      post :reset_discount
    end
    resource :shipping_address, only: [:edit, :update]
    resource :billing_address, only: [:edit, :update]
    resource :invoice, only: [:create]
  end

  resources :shipments, only: [:index]

  resources :events_catalog, only: [:index]

  resources :invoices, only: [:show]

  resources :products, only: [:new, :show, :create, :index, :edit, :update] do
    resources :supplies, only: [:new, :create]
    member do
      post :add_future_price, to: "product/future_price#add_future_price", as: "add_future_price"
    end
  end


  resources :coupons, only: [:new, :show, :create, :index]
  resources :time_promotions, only: [:new, :show, :create, :index]

  resources :customers, only: [:new, :create, :index, :update]

  resources :client_orders, only: [:index, :show, :new, :edit, :update, :create], controller: 'client/orders' do
    member do
      post :add_item
      post :remove_item
    end
  end
  post :login, to: "client/clients#login"
  get :logout, to: "client/clients#logout"
  get "clients", to: "client/clients#index"
  get "client/products", to: "client/products#index"

  mount RailsEventStore::Browser => "/res"
  mount Sidekiq::Web => '/sidekiq'
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/controllers/client/products_controller.rb
module Client
  class ProductsController < ApplicationController
    layout 'client_panel'

    def index
      render html: PublicOffer::ProductsList.build(view_context), layout: true
    end

  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/controllers/product/future_price_controller.rb
module Product
  class FuturePriceController < ApplicationController
    def add_future_price
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream:
            turbo_stream.append(
              "future_prices",
              partial: "/products/future_price",
              locals: {
                disabled: false,
                valid_since: nil,
                price: nil
              }
          )
        end
      end
    end
  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Products::Product.all
  end

  def show
    @product = Products::Product.find(params[:id])
  end

  def new
    @product_id = SecureRandom.uuid
  end

  def edit
    @product = Products::Product.find(params[:id])
  end

  def create
    ActiveRecord::Base.transaction do
      create_product(params[:product_id], params[:name])
      if params[:price].present?
        set_product_price(params[:product_id], params[:price])
      end
      if params[:vat_rate].present?
        set_product_vat_rate(params[:product_id], params[:vat_rate])
      end
    rescue ProductCatalog::AlreadyRegistered
      flash[:notice] = "Product was already registered"
      render "new"
    rescue Taxes::Product::VatRateNotApplicable
      flash[:notice] = "Selected VAT rate not applicable"
      render "new"
    else
      redirect_to products_path, notice: "Product was successfully created"
    end
  end

  def update
    if params[:price].present?
      set_product_price(params[:product_id], params[:price])
    end
    if params[:future_prices].present?
      params[:future_prices].each do |future_price|
        set_future_product_price(
          params[:product_id],
          future_price["price"],
          Time.zone.parse(future_price["start_time"]).utc
        )
      end
    end
    redirect_to products_path, notice: "Price was successfully updated"
  end

  private

  def create_product(product_id, name)
    command_bus.(create_product_cmd(product_id, name))
    command_bus.(name_product_cmd(product_id, name))
  end

  def set_product_price(product_id, price)
    command_bus.(set_product_price_cmd(product_id, price))
  end

  def set_future_product_price(product_id, price, valid_since)
    command_bus.(set_product_future_price_cmd(product_id, price, valid_since))
  end

  def set_product_vat_rate(product_id, vat_rate_code)
    vat_rate = Taxes::Configuration.available_vat_rates.find{|rate| rate.code == vat_rate_code}
    command_bus.(set_product_vat_rate_cmd(product_id, vat_rate))
  end

  def create_product_cmd(product_id, name)
    ProductCatalog::RegisterProduct.new(product_id: product_id)
  end

  def name_product_cmd(product_id, name)
    ProductCatalog::NameProduct.new(product_id: product_id, name: name)
  end

  def set_product_price_cmd(product_id, price)
    Pricing::SetPrice.new(product_id: product_id, price: price)
  end

  def set_product_vat_rate_cmd(product_id, vat_rate)
    Taxes::SetVatRate.new(product_id: product_id, vat_rate: vat_rate)
  end

  def set_product_future_price_cmd(product_id, price, valid_since)
    Pricing::SetFuturePrice.new(
      product_id: product_id,
      price: price,
      valid_since: valid_since
    )
  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/products/_future_price.html.erb
<% border_input_style = "#{disabled ? "border-none outline-none focus:outline-none focus:outline-none border-transparent focus:border-transparent focus:ring-0 focus:shadow-none shadow-none" : "border-gray-300 shadow-sm"}" %>

<div class="mt-2">
  <div class="inline">
    <label for="start_time" class="inline font-bold p-2">
      Start time:
      <%= datetime_field_tag :start_time, nil,
        value: valid_since&.strftime('%Y-%m-%dT%H:%M'),
        disabled: disabled,
        id: "start_time",
        name: "[future_prices][][start_time]",
        class: "#{border_input_style} mt-1 focus:ring-blue-500 focus:border-blue-500 inline-block sm:text-sm rounded-md"
      %>
    </label>
  </div>
  <div class="inline">
    <label for="price" class="font-bold p-2">
      Price:
      <%= number_field_tag :price, price,
        disabled: disabled,
        name: "[future_prices][][price]",
        min: 0,
        step: 0.01,
        required: true,
        class: "#{border_input_style} mt-1 focus:ring-blue-500 focus:border-blue-500 inline-block sm:text-sm rounded-md"
      %>
    </label>
  </div>
</div>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/products/edit.html.erb
<% content_for(:header) do %>
  Edit Product
<% end %>

<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= link_to 'Back', products_path %>
  <% end %>

  <%= primary_button_to(add_future_price_product_path(@product)) do %>
    Add future price
  <% end %>

  <%= primary_form_action_button do %>
    Update Product
  <% end %>
<% end %>

<%= form_tag({controller: "products", action: "update"}, method: "patch", id: "form") do %>
  <%= hidden_field_tag(:product_id, @product.id) %>

  <div>
    <p class="font-bold">Name</p>
    <%= @product.name %>
  </div>
  <div class="mt-2">
    <label for="vat_rate" class="block font-bold">
      VAT rate
    </label>
    <%= @product.vat_rate_code %>
  </div>
  <div class="mt-2">
    <label for="price" class="block font-bold">
      Price
    </label>
    <%= number_field_tag :price, @product.price, min: 0, step: 0.01, required: true, class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>

  <% if @product.future_prices_calendar.any? %>
    <label for="future_prices" class="mt-6 block font-bold">
      Future prices:
    </label>
    <% @product.future_prices_calendar.each do |entry| %>
      <%= render partial: "products/future_price", locals: {
        disabled: true,
        price: entry[:price],
        valid_since: entry[:valid_since] }
      %>
    <% end %>
  <% end %>
  <div id="future_prices" class="mt-2">
  </div>
<% end %>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/products/index.html.erb
<% content_for(:header) do %>
  Products
<% end %>

<% content_for(:actions) do %>
  <%= primary_action_button do %>
    <%= link_to 'New Product', new_product_path %>
  <% end %>
<% end %>

<table class="w-full">
  <thead>
    <tr>
      <th class="text-left py-2">Name</th>
      <th class="text-left py-2">Price</th>
      <th class="text-left py-2">VAT rate</th>
      <th class="text-right py-2">Stock Level</th>
    </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr class="border-t">
      <td class="py-2"><%= link_to product.name, product_path(product), class: "hover:underline text-blue-500" %></td>
      <td class="py-2"><%= number_to_currency product.price %></td>
      <td class="py-2"><%= product.vat_rate_code %></td>
      <td class="py-2 text-right"><%= product.stock_level %></td>
    </tr>
  <% end %>
  </tbody>
</table>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/products/new.html.erb
<% content_for(:header) do %>
  New Product
<% end %>

<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= link_to 'Back', products_path %>
  <% end %>

  <%= primary_form_action_button do %>
    Create Product
  <% end %>
<% end %>

<%= form_tag({controller: "products", action: "create"}, method: "post", id: "form") do %>
  <%= hidden_field_tag(:product_id, @product_id) %>

  <div>
    <label for="name" class="block font-bold">
      Name
    </label>
    <%= text_field_tag :name, "", required: true, class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>
  <div class="mt-2">
    <label for="price" class="block font-bold">
      Price
    </label>
    <%= number_field_tag :price, nil, min: 0, step: 0.01, required: true, class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>
  <div class="mt-2">
    <label for="vat_rate" class="block font-bold">
      VAT rate
    </label>
    <%= select_tag :vat_rate, options_from_collection_for_select(Taxes::Configuration.available_vat_rates, :code, :code), class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md" %>
  </div>
<% end %>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/products/show.html.erb
<% content_for(:header) do %>
  Product
<% end %>

<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= link_to 'Back', products_path %>
  <% end %>

  <%= primary_action_button do %>
    <%= link_to 'Supply', new_product_supply_path(product_id: @product.id) %>
  <% end %>
<% end %>

<dl class="mb-8">
  <dt class="font-bold">Name</dt>
  <dd class="mb-2"><%= @product.name %></dd>
  <dt class="font-bold">Price</dt>
  <dd class="mb-2"><%= number_to_currency @product.price %>
    <%= link_to "Edit product price",
                edit_product_path(@product.id),
                class: 'px-2 py-1 border rounded-md shadow-sm text-xs font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 border-transparent text-white bg-blue-600 hover:bg-blue-700'
    %>
  </dd>
  <dt class="font-bold">VAT rate</dt>
  <dd class="mb-2"><%= @product.vat_rate_code %></dd>
  <dt class="font-bold">Stock Level</dt>
  <dd class="mb-2 mt-2"><%= @product.stock_level %></dd>
</dl>

<% if @product.future_prices_calendar.any? %>
  <dl class="pt-4">
    <label for="future_prices" class="mt-6 block font-bold">
      Future prices:
    </label>
    <% @product.future_prices_calendar.each do |entry| %>
      <%= render partial: "products/future_price", locals: {
        disabled: true,
        price: entry[:price],
        valid_since: entry[:valid_since] }
      %>
    <% end %>
    </dt>
  </dl>
<% end %>