RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "orders#index"

  resources :orders, only: [:index, :show, :new, :edit, :create] do
    collection do
      post :expire
    end
    member do
      post :add_item
      post :remove_item
      post :pay
      post :cancel
      get :edit_discount
      post :update_discount
      post :reset_discount
    end
    resource :shipping_address, only: [:edit, :update]
    resource :billing_address, only: [:edit, :update]
    resource :invoice, only: [:create]
  end

  resources :shipments, only: [:index]

  resources :events_catalog, only: [:index]

  resources :invoices, only: [:show]

  resources :products, only: [:new, :show, :create, :index, :edit, :update] do
    resources :supplies, only: [:new, :create]
    member do
      post :add_future_price, to: "product/future_price#add_future_price", as: "add_future_price"
    end
  end


  resources :coupons, only: [:new, :show, :create, :index]
  resources :time_promotions, only: [:new, :show, :create, :index]

  resources :customers, only: [:new, :create, :index, :update]

  resources :client_orders, only: [:index, :show, :new, :edit, :update, :create], controller: 'client/orders' do
    member do
      post :add_item
      post :remove_item
    end
  end
  post :login, to: "client/clients#login"
  get :logout, to: "client/clients#logout"
  get "clients", to: "client/clients#index"
  get "client/products", to: "client/products#index"

  mount RailsEventStore::Browser => "/res"
  mount Sidekiq::Web => '/sidekiq'
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customers::Customer.all
  end

  def new
    @customer_id = SecureRandom.uuid
  end

  def create
    create_customer(params[:customer_id], params[:name])
  rescue Crm::Customer::AlreadyRegistered
    flash[:notice] = "Customer was already registered"
    render "new"
  else
    redirect_to customers_path, notice: "Customer was successfully created"
  end

  def update
    promote_to_vip(params[:id])
  rescue Crm::Customer::AlreadyVip
    redirect_to customers_path, notice: "Customer was marked as vip"
  else
    redirect_to customers_path, notice: "Customer was promoted to VIP"
  end

  private

  def create_customer(customer_id, name)
    command_bus.(create_customer_cmd(customer_id, name))
  end

  def promote_to_vip(customer_id)
    command_bus.(promote_to_vip_cmd(customer_id))
  end

  def create_customer_cmd(customer_id, name)
    Crm::RegisterCustomer.new(customer_id: customer_id, name: name)
  end

  def promote_to_vip_cmd(customer_id)
    Crm::PromoteCustomerToVip.new(customer_id: customer_id)
  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/customers/index.html.erb
<% content_for(:header) do %>
  Customers
<% end %>

<% content_for(:actions) do %>
  <%= primary_action_button do %>
    <%= link_to 'New Customer', new_customer_path %>
  <% end %>
<% end %>

<table class="w-full">
  <thead>
    <tr>
      <th class="text-left py-2">Name</th>
      <th class="text-center py-2">Vip</th>
      <th class="text-right py-2">Paid oders summary</th>
    </tr>
  </thead>

  <tbody>
  <% @customers.each do |customer| %>
    <tr class="border-t">

        <td class="py-2"><%= customer.name %></td>
        <td class="py-2 text-center">
          <%- if customer.vip %>
            Already a VIP
          <%- else %>
            <%= form_with(model: customer, url: customer_path(customer.id), id: "form#{customer.id}") do |form| %>
              <%= action_button "border-transparent text-white bg-blue-600 hover:bg-blue-700", type: "submit",
                                form: "form#{customer.id}" do %>
                  Promote to Vip
              <% end %>
            <% end %>
          <% end %>
        </td>
        <td class="py-2 text-right">
          <%= number_to_currency(customer.paid_orders_summary) %>
        </td>
    </tr>
  <% end %>
  </tbody>
</table>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/customers/new.html.erb
<% content_for(:header) do %>
  New Customer
<% end %>

<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= link_to 'Back', customers_path %>
  <% end %>

  <%= primary_form_action_button do %>
    Create Customer
  <% end %>
<% end %>

<%= form_tag({controller: "customers", action: "create"}, method: "post", id: "form") do %>
  <%= hidden_field_tag(:customer_id, @customer_id) %>

  <label for="customer" class="block font-bold">
    Name
  </label>
  <%= text_field_tag :name, "", required: true, class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md" %>
<% end %>