RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "orders#index"

  resources :orders, only: [:index, :show, :new, :edit, :create] do
    collection do
      post :expire
    end
    member do
      post :add_item
      post :remove_item
      post :pay
      post :cancel
      get :edit_discount
      post :update_discount
      post :reset_discount
    end
    resource :shipping_address, only: [:edit, :update]
    resource :billing_address, only: [:edit, :update]
    resource :invoice, only: [:create]
  end

  resources :shipments, only: [:index]

  resources :events_catalog, only: [:index]

  resources :invoices, only: [:show]

  resources :products, only: [:new, :show, :create, :index, :edit, :update] do
    resources :supplies, only: [:new, :create]
    member do
      post :add_future_price, to: "product/future_price#add_future_price", as: "add_future_price"
    end
  end


  resources :coupons, only: [:new, :show, :create, :index]
  resources :time_promotions, only: [:new, :show, :create, :index]

  resources :customers, only: [:new, :create, :index, :update]

  resources :client_orders, only: [:index, :show, :new, :edit, :update, :create], controller: 'client/orders' do
    member do
      post :add_item
      post :remove_item
    end
  end
  post :login, to: "client/clients#login"
  get :logout, to: "client/clients#logout"
  get "clients", to: "client/clients#index"
  get "client/products", to: "client/products#index"

  mount RailsEventStore::Browser => "/res"
  mount Sidekiq::Web => '/sidekiq'
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def event_store
    Rails.configuration.event_store
  end

  def command_bus
    Rails.configuration.command_bus
  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/helpers/application_helper.rb
module ApplicationHelper
  def navigation_link(label, path)
    current_link_to label, path,
      class: class_names(
        "px-3 py-2 rounded-md text-sm font-medium",
        "bg-gray-900 text-white" => current_page?(path),
        "text-gray-300 hover:bg-gray-700 hover:text-white" => !current_page?(path)
      )
  end

  def action_button(css_classes, type: "button", form: nil)
    content_tag "span", class: "sm:ml-3" do
      content_tag "button", type: type, form: form, class: class_names(
        "inline-flex items-center px-4 py-2 border rounded-md shadow-sm text-sm font-medium",
        "focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500",
        css_classes
      ) do
        yield
      end
    end
  end

  def primary_form_action_button(&block)
    action_button(
      "border-transparent text-white bg-blue-600 hover:bg-blue-700",
      type: "submit",
      form: "form",
      &block
    )
  end

  def primary_action_button(type: "button", &block)
    action_button(
      "border-transparent text-white bg-blue-600 hover:bg-blue-700",
      type: type,
      &block
    )
  end

  def secondary_action_button(type: "button", form: nil, &block)
    action_button(
      "border-gray-300 text-gray-700 bg-white hover:bg-gray-50",
      &block
    )
  end

  def primary_button_to(action, &block)
    content_tag("form", action: action, method: :post) do
      concat primary_action_button(type: "submit", &block)
      concat tag.input type: "hidden", authenticity_token: form_authenticity_token
    end
  end

  def stream_browser_path(stream_name)
    File.join(ruby_event_store_browser_app_path, "streams", stream_name)
  end

  def stream_browser_link(link_name, stream_name, options = {})
    link_to link_name, stream_browser_path(CGI.escape(stream_name)),
            options.merge(data: { turbo: false })
  end

  def order_history_link(id)
    stream_browser_link("History", "Ordering::Order$#{id}")
  end

  def current_link_to(label, path, **kwargs)
    link_to(label, path,
      **kwargs.merge(Hash(({ "aria-current": "page" } if current_page?(path))))
    )
  end

  def class_names(*unconditional_classes, **conditional_classes)
    [
      *unconditional_classes,
      *conditional_classes.filter_map { |k, v| k if v }
    ].join(" ")
  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/application/_client_top_navigation.html.erb
<nav class="bg-gray-800">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <h1 class="text-gray-600 uppercase tracking-tight font-bold">
            ecommerce
          </h1>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <%= navigation_link "Client View", clients_path %>
            <%= navigation_link "Products", client_products_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/application/_footer.html.erb
<footer class="bg-gray-100" aria-labelledby="footer-heading">
  <h2 id="footer-heading" class="sr-only">Footer</h2>
  <div class="max-w-6xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
    <div class="xl:grid xl:grid-cols-6 xl:gap-8">
      <div class="space-y-8 xl:col-span-3">
        <p class="text-gray-500 text-base">
          Ecommerce application with CQRS and Event Sourcing built on Rails
          and <%= link_to "Rails Event Store", "https://railseventstore.org", class: "bg-link font-semibold text-gray-800" %>.
        </p>
      </div>
      <div class="mt-12 grid grid-cols-1 gap-8 xl:mt-0 xl:col-span-3">
        <div class="md:grid md:grid-cols-3 md:gap-8">
          <div>
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Observe
            </h3>
            <ul role="list" class="mt-4 space-y-4">
              <%
                { "Errors"       => "https://app.honeybadger.io/project/9d53P8W1ML",
                  "Analytics"    => "https://plausible.io/ecommerce.arkademy.dev",
                  "Events"       => ruby_event_store_browser_app_path,
                  "Performance"  => "https://oss.skylight.io/app/applications/pTvtzqO3cOxV/recent/6h/endpoints"
                }.each do |label, url|
              %>
              <li>
                <%= link_to label, url, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <% end %>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Improve
            </h3>
            <ul role="list" class="mt-4 space-y-4">
              <%
                { "Issues"      => "https://github.com/RailsEventStore/ecommerce/issues",
                  "Source Code" => "https://github.com/RailsEventStore/ecommerce",
                }.each do |label, url|
              %>
              <li>
                <%= link_to label, url, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <% end %>
            </ul>
          </div>
          <div class="mt-12 md:mt-0">
            <h3 class="text-sm font-semibold text-gray-400 tracking-wider uppercase">
              Learn
            </h3>
            <ul role="list" class="mt-4 space-y-4">
              <%
                { "DDD as Low-Code" => "https://www.youtube.com/watch?v=yohu6qx8-dU",
                  "arkademy.dev"    => "https://arkademy.dev",
                }.each do |label, url|
              %>
              <li>
                <%= link_to label, url, class: "text-base text-gray-500 hover:text-gray-900" %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/application/_top_navigation.html.erb
<nav class="bg-gray-800">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <h1 class="text-gray-600 uppercase tracking-tight font-bold">
            ecommerce
          </h1>
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <%= navigation_link "Orders", orders_path %>
            <%= navigation_link "Shipments", shipments_path %>
            <%= navigation_link "Products", products_path %>
            <%= navigation_link "Coupons", coupons_path %>
            <%= navigation_link "Time Promotions", time_promotions_path %>
            <%= navigation_link "Customers", customers_path %>
            <%= navigation_link "Client View", clients_path %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/application/_tracking.html.erb
<script defer data-domain="ecommerce.arkademy.dev" src="https://plausible.io/js/plausible.js"></script>