RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root "orders#index"

  resources :orders, only: [:index, :show, :new, :edit, :create] do
    collection do
      post :expire
    end
    member do
      post :add_item
      post :remove_item
      post :pay
      post :cancel
      get :edit_discount
      post :update_discount
      post :reset_discount
    end
    resource :shipping_address, only: [:edit, :update]
    resource :billing_address, only: [:edit, :update]
    resource :invoice, only: [:create]
  end

  resources :shipments, only: [:index]

  resources :events_catalog, only: [:index]

  resources :invoices, only: [:show]

  resources :products, only: [:new, :show, :create, :index, :edit, :update] do
    resources :supplies, only: [:new, :create]
    member do
      post :add_future_price, to: "product/future_price#add_future_price", as: "add_future_price"
    end
  end


  resources :coupons, only: [:new, :show, :create, :index]
  resources :time_promotions, only: [:new, :show, :create, :index]

  resources :customers, only: [:new, :create, :index, :update]

  resources :client_orders, only: [:index, :show, :new, :edit, :update, :create], controller: 'client/orders' do
    member do
      post :add_item
      post :remove_item
    end
  end
  post :login, to: "client/clients#login"
  get :logout, to: "client/clients#logout"
  get "clients", to: "client/clients#index"
  get "client/products", to: "client/products#index"

  mount RailsEventStore::Browser => "/res"
  mount Sidekiq::Web => '/sidekiq'
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/controllers/client/orders_controller.rb
module Client
  class OrdersController < ApplicationController

    layout 'client_panel'

    def index
      render html: ClientOrders::OrdersList.build(view_context, cookies[:client_id]), layout: true
    end

    def new
      @order_id = SecureRandom.uuid
      @products = ClientOrders::Product.all
      render 'edit'
    end

    def create
      command_bus.(Ordering::SubmitOrder.new(order_id: params[:order_id]))
      command_bus.(Crm::AssignCustomerToOrder.new(customer_id: cookies[:client_id], order_id: params[:order_id]))
      redirect_to client_order_path(params[:order_id]),
                  notice: "Your order is being submitted"
    end

    def show
      @order = ClientOrders::Order.find_by_order_uid(params[:id])
      @order_lines = ClientOrders::OrderLine.where(order_uid: params[:id])
    end

    def edit
      @order_id = params[:id]
      @order_lines = ClientOrders::OrderLine.where(order_uid: params[:id])
      @products = ClientOrders::Product.all
    end

    def add_item
      read_model = ClientOrders::OrderLine.where(order_uid: params[:id], product_id: params[:product_id]).first
      if Availability::Product.exists?(["uid = ? and available < ?", params[:product_id], (read_model&.product_quantity || 0) + 1])
        redirect_to edit_client_order_path(params[:id]),
                    alert: "Product not available in requested quantity!" and return
      end
      ActiveRecord::Base.transaction do
        command_bus.(
          Ordering::AddItemToBasket.new(
            order_id: params[:id],
            product_id: params[:product_id]
          )
        )
      end
    end

    def remove_item
      command_bus.(
        Ordering::RemoveItemFromBasket.new(
          order_id: params[:id],
          product_id: params[:product_id]
        )
      )
    rescue Ordering::Order::CannotRemoveZeroQuantityItem
      redirect_to edit_client_order_path(params[:id]),
                  alert: "Cannot remove the product with 0 quantity"
    end

  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Orders::Order.order("id DESC").page(params[:page]).per(10)
  end

  def show
    @order = Orders::Order.find_by_uid(params[:id])
    @order_lines = Orders::OrderLine.where(order_uid: @order.uid)
    @shipment = Shipments::Shipment.find_by(order_uid: @order.uid)
    @invoice = Invoices::Invoice.find_or_initialize_by(order_uid: @order.uid)
  end

  def new
    redirect_to edit_order_path(SecureRandom.uuid)
  end

  def edit
    @order_id = params[:id]
    @order = Orders::Order.find_by_uid(params[:id])
    @order_lines = Orders::OrderLine.where(order_uid: params[:id])
    @products = Products::Product.all
    @customers = Customers::Customer.all
    @time_promotions = TimePromotions::TimePromotion.current

    render :edit,
           locals: {
             discounted_value: @order&.discounted_value || 0,
             total_value: @order&.total_value || 0,
             percentage_discount: @order&.percentage_discount
           }
  end

  def edit_discount
    @order_id = params[:id]
  end

  def update_discount
    @order_id = params[:id]
    if Orders::Order.find_by_uid(params[:id]).percentage_discount
      command_bus.(Pricing::ChangePercentageDiscount.new(order_id: @order_id, amount: params[:amount]))
    else
      command_bus.(Pricing::SetPercentageDiscount.new(order_id: @order_id, amount: params[:amount]))
    end

    redirect_to edit_order_path(@order_id)
  end

  def reset_discount
    @order_id = params[:id]
    command_bus.(Pricing::ResetPercentageDiscount.new(order_id: @order_id))

    redirect_to edit_order_path(@order_id)
  end

  def add_item
    read_model = Orders::OrderLine.where(order_uid: params[:id], product_id: params[:product_id]).first
    if Availability::Product.exists?(["uid = ? and available < ?", params[:product_id], (read_model&.quantity || 0) + 1])
      redirect_to edit_order_path(params[:id]),
                  alert: "Product not available in requested quantity!" and return
    end
    ActiveRecord::Base.transaction do
      command_bus.(Ordering::AddItemToBasket.new(order_id: params[:id], product_id: params[:product_id]))
    end
    head :ok
  end

  def remove_item
    command_bus.(Ordering::RemoveItemFromBasket.new(order_id: params[:id], product_id: params[:product_id]))
    head :ok
  rescue Ordering::Order::CannotRemoveZeroQuantityItem
    redirect_to edit_order_path(params[:id]), alert: "Cannot remove the product with 0 quantity"
  end

  def create
    ApplicationRecord.transaction { submit_order(params[:order_id], params[:customer_id]) }
    redirect_to order_path(params[:order_id]), notice: "Your order is being submitted"
  rescue Crm::Customer::NotExists
    redirect_to order_path(params[:order_id]), alert: "Order can not be submitted! Customer does not exist."
  end

  def expire
    Orders::Order
      .where(state: "Draft")
      .find_each { |order| command_bus.(Ordering::SetOrderAsExpired.new(order_id: order.uid)) }
    redirect_to root_path
  end

  def pay
    ActiveRecord::Base.transaction do
      authorize_payment(params[:id])
      capture_payment(params[:id])
      flash[:notice] = "Order paid successfully"
    rescue Payments::Payment::AlreadyAuthorized
      flash[:alert] = "Payment was already authorized"
    rescue Payments::Payment::AlreadyCaptured
      flash[:alert] = "Payment was already captured"
    rescue Payments::Payment::NotAuthorized
      flash[:alert] = "Payment wasn't yet authorized"
    rescue Ordering::Order::NotSubmitted
      flash[:alert] = "You can't pay for an order which is not submitted"
    end
    redirect_to orders_path
  end

  def cancel
    command_bus.(Ordering::CancelOrder.new(order_id: params[:id]))
    redirect_to root_path, notice: "Order cancelled"
  end

  private

  def submit_order(order_id, customer_id)
    command_bus.(Ordering::SubmitOrder.new(order_id: order_id))
    command_bus.(Crm::AssignCustomerToOrder.new(order_id: order_id, customer_id: customer_id))
  end

  def authorize_payment(order_id)
    command_bus.call(authorize_payment_cmd(order_id))
  end

  def capture_payment(order_id)
    command_bus.call(capture_payment_cmd(order_id))
  end

  def authorize_payment_cmd(order_id)
    Payments::AuthorizePayment.new(order_id: order_id)
  end

  def capture_payment_cmd(order_id)
    Payments::CapturePayment.new(order_id: order_id)
  end
end

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/orders/edit.html.erb
<%= turbo_stream_from "orders_order_#{@order_id}" %>

<% content_for(:header) do %>
  Order
<% end %>

<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= link_to 'Back', orders_path %>
  <% end %>

  <%= secondary_action_button do %>
    <%= link_to "Edit discount", edit_discount_order_path(@order_id) %>
  <% end %>

  <%= secondary_action_button do %>
    <%= link_to "Edit Shipping Address", edit_order_shipping_address_path(@order_id) %>
  <% end %>

  <%= secondary_action_button do %>
    <%= link_to "Edit Billing Address", edit_order_billing_address_path(@order_id) %>
  <% end %>

  <%= primary_form_action_button do %>
    Submit Order
  <% end %>
<% end %>

<table class="w-full">
  <thead>
    <tr class="border-b">
      <th class="text-left py-2">Product</th>
      <th class="text-left py-2">Quantity</th>
      <th class="text-left py-2">Price</th>
      <th class="text-left py-2" colspan="3">Value</th>
    </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr class="border-b">
      <% order_line = @order_lines.find{|order_line| order_line.product_id == product.id} %>
      <td class="py-2"><%= product.name %></td>
      <td class="py-2" id="<%= "orders_order_#{product.id}_quantity" %>"><%= order_line.try(&:quantity) || 0 %></td>
      <td class="py-2"><%= number_to_currency(product.price) %></td>
      <td class="py-2" id="<%= "orders_order_#{product.id}_value" %>"><%= number_to_currency(order_line.try(&:value)) %></td>
      <td class="py-2 text-right"><%= button_to "Add", add_item_order_path(id: @order_id, product_id: product.id), class: "hover:underline text-blue-500" %></td>
      <td class="py-2 text-right"><%= button_to "Remove", remove_item_order_path(id: @order_id, product_id: product.id), class: "hover:underline text-blue-500" %></td>
    </tr>
  <% end %>
  </tbody>
  <tfoot class="border-t-4">
    <% if discounted_value != total_value %>
      <tr class="border-t">
        <td class="py-2" colspan="3">Before discounts</td>
        <td class="py-2" id="<%= "orders_order_#{@order_id}_total_value" %>"><%= number_to_currency(total_value) %></td>
      </tr>
    <% end %>
    <% if percentage_discount %>
      <tr class="border-t">
        <td class="py-2" colspan="3">General discount</td>
        <td class="py-2" id="<%= "orders_order_#{@order_id}_percentage_discount" %>"><%= percentage_discount %>%</td>
        <td class="py-2 text-right" colspan="2"><%= button_to "Reset", reset_discount_order_path(id: @order_id), {method: :post, class: "hover:underline text-blue-500"} %></td>
      </tr>
    <% end %>
    <% if @time_promotions.present? %>
      <% @time_promotions.each do |time_promotion| %>
        <tr class="border-t">
          <td class="py-2" colspan="3">Promotion: <%= time_promotion.label %> (if you buy before <%= time_promotion.end_time %>)</td>
          <td class="py-2"><%= time_promotion.discount %>%</td>
        </tr>
      <% end %>
    <% end %>
    <tr class="border-t">
      <td class="py-2" colspan="3">Total</td>
      <td class="py-2 font-bold" id="<%= "orders_order_#{@order_id}_discounted_value" %>"><%= number_to_currency(discounted_value) %></td>
    </tr>
  </tfoot>
</table>

<%= form_tag({controller: "orders", action: "create"}, method: "post", id: "form") do %>
  <%= hidden_field_tag(:order_id, @order_id) %>

  <div class="mt-8">
    <label for="customer" class="block font-bold">
      Customer
    </label>
    <%= select_tag(:customer_id, options_from_collection_for_select(@customers, :id, :name), id: "customer", class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md") %>
  </div>
<% end %>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/orders/edit_discount.html.erb
<% content_for(:header) do %>
  Discount
<% end %>

<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= link_to 'Back', edit_order_path(@order_id) %>
  <% end %>

  <%= primary_form_action_button do %>
    Set Discount
  <% end %>
<% end %>

<%= form_tag({controller: "orders", action: "update_discount"}, method: "post", id: "form") do %>
  <%= hidden_field_tag(:order_id, @order_id) %>
  <label for="discount" class="block font-bold">
    Percentage
  </label>
  <%= number_field_tag :amount, 20, min: 10, max: 100, step: 10, id: "discount", class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md" %>
<% end %>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/orders/index.html.erb
<% content_for(:header) do %>
  Orders
<% end %>

<% content_for(:actions) do %>
  <%= button_to("Expire orders", expire_orders_path, class: "inline-flex items-center px-4 py-2 border rounded-md shadow-sm text-sm font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-50 border-gray-300 text-gray-700 bg-white hover:bg-gray-50 mr-2") %>

  <%= primary_action_button do %>
    <%= link_to 'New order', new_order_path, data: { turbo: false } %>
  <% end %>
<% end %>

<table class="w-full">
  <thead>
    <tr>
      <th class="text-left py-2">Number</th>
      <th class="text-left py-2">Customer</th>
      <th class="text-right py-2">State</th>
    </tr>
  </thead>

  <tbody>
  <% @orders.each do |order| %>
    <%= turbo_stream_from "orders_order_#{order.uid}" %>
    <tr class="border-t">
      <td class="py-2"><%= link_to order.number || 'Not submitted', order_path(order.uid), class: "text-blue-500 hover:underline" %></td>
      <td class="py-2"><%= order.customer %></td>
      <td class="py-2 text-right" id="<%= "orders_order_#{order.uid}_state" %>"><%= order.state %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<div class="mt-8 hidden sm:flex-1 sm:flex sm:items-center sm:justify-between">
  <div>
    <%= page_entries_info @orders %>
  </div>
  <div>
    <%= paginate @orders %>
  </div>
</div>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/orders/new.html.erb
<% content_for(:header) do %>
  New Order
<% end %>

<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= link_to 'Back', orders_path %>
  <% end %>

  <%= primary_form_action_button do %>
    Submit Order
  <% end %>
<% end %>

<table class="w-full">
  <thead>
    <tr>
      <th class="text-left py-2">Product</th>
      <th class="text-left py-2" colspan="3">Price</th>
    </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
    <tr class="border-t">
      <td class="py-2"><%= product.name %></td>
      <td class="py-2"><%= number_to_currency(product.price) %></td>
      <td class="py-2">
        <%= link_to "Add", add_item_order_path(id: @order_id, product_id: product.id), {method: :post, class: "text-blue-500 hover:underline"} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= form_tag({controller: "orders", action: "create"}, method: "post", id: "form") do %>
  <%= hidden_field_tag(:order_id, @order_id) %>

  <div class="mt-8">
    <label for="customer" class="block font-bold">
      Customer
    </label>
    <%= select_tag(:customer_id, options_from_collection_for_select(@customers, :id, :name), id: "customer", class: "mt-1 focus:ring-blue-500 focus:border-blue-500 block shadow-sm sm:text-sm border-gray-300 rounded-md") %>
  </div>
<% end %>

RubyOnRails/Rails-Mvc-Cqrs-Order-App/rails_application/app/views/orders/show.html.erb
<% content_for(:header) do %>
  Order <%= @order.number %>
<% end %>
<%= turbo_stream_from "orders_order_#{@order.uid}" %>
<% content_for(:actions) do %>
  <%= secondary_action_button do %>
    <%= order_history_link(@order.uid) %>
  <% end %>

  <%= secondary_action_button do %>
    <%= link_to "Invoice", invoice_path(@order.uid) %>
  <% end if @invoice.issued? %>

  <%= secondary_action_button do %>
    <%= link_to 'Back', orders_path %>
  <% end %>

  <%= primary_action_button do %>
    <%= link_to 'Edit', edit_order_path(@order.uid) %>
  <% end if @order.state == "Draft" %>

  <% if @order.state == "Submitted" %>
    <%= button_to("Pay", pay_order_path(@order.uid), class: "mr-3 ml-3 inline-flex items-center px-4 py-2 border rounded-md shadow-sm text-sm font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 border-transparent text-white bg-blue-600 hover:bg-blue-700") %>
  <% end %>

  <% if (@order.state != "Cancelled" && @order.state != "Paid") %>
    <%= button_to("Cancel Order", cancel_order_path(@order.uid), class: "inline-flex items-center px-4 py-2 border rounded-md shadow-sm text-sm font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-50 border-gray-300 text-gray-700 bg-white hover:bg-gray-50") %>
  <% end %>
<% end %>

<dl class="mb-8">
  <dt class="font-bold">Customer</dt>
  <dd class="mb-2"><%= @order.customer || "None" %></dd>
  <dt class="font-bold">State</dt>
  <dd class="mb-2" id="<%= "orders_order_#{@order.uid}_state" %>"><%= @order.state %></dd>
  <dt class="font-bold">Shipping Details</dt>
  <dd class="mb-2">
    <% unless @shipment %>
      Shipping address is missing.
    <% end %>
  </dd>
  <dd class="mb-2">
    <% unless @shipment %>
      <%= link_to "Add shipment address",
                  edit_order_shipping_address_path(@order.uid),
                  class: 'px-2 py-1 border rounded-md shadow-sm text-xs font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 border-transparent text-white bg-blue-600 hover:bg-blue-700'
      %>
    <% else %>
      Your shipment has been queued for processing.
    <% end %>
  </dd>
  <% if @order.state != "Draft" %>
    <dt class="font-bold">Billing Details</dt>
    <dd class="mb-2">
      <% if @invoice.issued? %>
        <%= link_to @invoice.number, invoice_path(@order.uid) %>
      <% elsif !@invoice.address_present? %>
        Billing address is missing.
        <%= link_to "Add billing address",
                    edit_order_billing_address_path(@order.uid),
                    class: 'px-2 py-1 border rounded-md shadow-sm text-xs font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 border-transparent text-white bg-blue-600 hover:bg-blue-700'
        %>
      <% else %>
        Invoice not issued
        <%= button_to "Issue now",
                    order_invoice_path(@order.uid),
                    class: 'px-2 py-1 border rounded-md shadow-sm text-xs font-medium focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 border-transparent text-white bg-blue-600 hover:bg-blue-700'
        %>
      <% end %>
    </dd>
  <% end %>
</dl>

<table class="w-full">
  <thead>
    <tr>
      <th class="text-left py-2">Product</th>
      <th class="text-left py-2">Quantity</th>
      <th class="text-left py-2">Price</th>
      <th class="text-right py-2">Value</th>
    </tr>
  </thead>

  <tbody>
  <% @order_lines.each do |item| %>
    <tr class="border-t">
      <td class="py-2"><%= item.product_name %></td>
      <td class="py-2"><%= item.quantity %></td>
      <td class="py-2"><%= number_to_currency(item.price) %></td>
      <td class="py-2 text-right"><%= number_to_currency(item.value) %></td>
    </tr>
  <% end %>
  </tbody>
  <tfoot class="border-t-4">
    <% if @order.discounted_value != @order.total_value %>
      <tr class="border-t">
        <td class="py-2" colspan="3">Before discounts</td>
        <td class="py-2 text-right" id="before-discounts-value"><%= number_to_currency(@order.total_value) %></td>
      </tr>
    <% end %>
    <% if @order.percentage_discount %>
    <tr class="border-t">
      <td class="py-2" colspan="3">General discount</td>
      <td class="py-2 text-right"><%= @order.percentage_discount %>%</td>
    </tr>
    <% end %>

    <tr class="border-t">
      <td class="py-2" colspan="3">Total</td>
      <td class="py-2 text-right font-bold"><%= number_to_currency(@order.discounted_value) %></td>
    </tr>
  </tfoot>
</table>